name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Define the OS to run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Specify the version of Java that is installed
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      # Run the build script
      - name: Install dependencies, set environment variables, and build the package
        run: ./.github/scripts/build.sh
        shell: bash

  test:
    runs-on: ubuntu-18.04
    # Specify that the build job is a prerequisite
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      # Run sbt tests
      - name: Run tests
        run: ./build/sbt test

